blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/TEU_USER/omnikey/discussions
    about: Please ask questions here instead of opening an issue.
